Repository danny-avila/LibreChat, pull requests merged in 2025-02, with the labels that each got.

#5754 🧹 chore: Enhance Issue Templates with Emoji Labels
  .github/ISSUE_TEMPLATE/BUG-REPORT.yml
  .github/ISSUE_TEMPLATE/FEATURE-REQUEST.yml
  .github/ISSUE_TEMPLATE/QUESTION.yml
Labels: 🧹 chore

#5726 🔇 a11y: Silence Unnecessary Icons for Screen Readers
  .github/ISSUE_TEMPLATE/BUG-REPORT.yml
  client/src/components/Chat/Input/TemporaryChat.tsx
  client/src/components/Endpoints/MinimalIcon.tsx
  client/src/components/Input/ModelSelect/TemporaryChat.tsx
  client/src/components/Nav/Bookmarks/BookmarkNav.tsx
  client/src/components/Prompts/AdminSettings.tsx
  client/src/components/Prompts/Command.tsx
  client/src/components/Prompts/Description.tsx
  client/src/components/Prompts/Groups/CategoryIcon.tsx
  client/src/components/Prompts/PromptVariables.tsx
  client/src/components/SidePanel/Agents/AdminSettings.tsx
  client/src/components/SidePanel/Agents/ModelPanel.tsx
  client/src/components/SidePanel/Files/PanelTable.tsx
  client/src/routes/Layouts/DashBreadcrumb.tsx
Labels: ♿ a11y

#5737 🧹 chore: Migrate to Flat ESLint Config & Update Prettier Settings
  .eslintrc.js
  .github/workflows/backend-review.yml
  .github/workflows/eslint-ci.yml
  .prettierrc
  client/package.json
  client/tsconfig.json
  eslint.config.mjs
  package-lock.json
  package.json
  prettier.config.js
Labels: 📦 dependencies, 💥 breaking change, 🧹 chore

#5762 🤖 ci: locize-pull-published-sync-pr.yml
  .github/workflows/locize-pull-published-sync-pr.yml
Labels: 🌍 i18n, 🤖 ci/cd

#5769 📜 ci: Consolidate Locize Workflows for Missing Keys & PR Creation
  .github/workflows/locize-i18n-sync.yml
  .github/workflows/locize-push-missing-keys.yml
Labels: 🔨 refactor, 🤖 ci/cd

#5693 ✨feat: OAuth for Actions
  api/cache/getLogStores.js
  api/cache/keyvRedis.js
  api/config/index.js
  api/models/Token.js
  api/models/schema/tokenSchema.js
  api/package.json
  api/server/controllers/AskController.js
  api/server/controllers/EditController.js
  api/server/controllers/agents/request.js
  api/server/index.js
  api/server/routes/actions.js
  api/server/routes/agents/actions.js
  api/server/routes/assistants/actions.js
  api/server/routes/index.js
  api/server/services/ActionService.js
  api/server/services/Endpoints/agents/initialize.js
  api/server/services/TokenService.js
  api/server/services/ToolService.js
  api/typedefs.js
  client/src/components/Chat/Messages/Content/Files.tsx
  client/src/components/Chat/Messages/Content/InProgressCall.tsx
  client/src/components/Chat/Messages/Content/Part.tsx
  client/src/components/Chat/Messages/Content/ProgressText.tsx
  client/src/components/Chat/Messages/Content/ToolCall.tsx
  client/src/components/Chat/Messages/Content/ToolPopover.tsx
  client/src/components/Prompts/Groups/GroupSidePanel.tsx
  client/src/components/SidePanel/Agents/ActionsAuth.tsx
  client/src/components/SidePanel/Agents/ActionsInput.tsx
  client/src/components/SidePanel/Agents/ActionsPanel.tsx
  client/src/components/SidePanel/Agents/ActionsTable/Table.tsx
  client/src/components/SidePanel/Builder/ActionCallback.tsx
  client/src/components/SidePanel/Builder/ActionsAuth.tsx
  client/src/components/SidePanel/Builder/ActionsInput.tsx
  client/src/components/SidePanel/Builder/ActionsPanel.tsx
  client/src/components/SidePanel/Files/PanelFileCell.tsx
  client/src/components/ui/OGDialogTemplate.tsx
  client/src/hooks/SSE/useStepHandler.ts
  client/src/locales/en/translation.json
  client/src/locales/nl/translation.json
  eslint.config.mjs
  package-lock.json
  packages/data-provider/package.json
  packages/data-provider/specs/actions.spec.ts
  packages/data-provider/src/actions.ts
  packages/data-provider/src/bedrock.ts
  packages/data-provider/src/config.ts
  packages/data-provider/src/schemas.ts
  packages/data-provider/src/types/agents.ts
  packages/data-provider/src/types/assistants.ts
  packages/data-provider/tsconfig.json
  packages/mcp/babel.config.cjs
  packages/mcp/jest.config.mjs
  packages/mcp/package.json
  packages/mcp/src/flow/manager.spec.ts
  packages/mcp/src/flow/manager.ts
  packages/mcp/src/flow/types.ts
  packages/mcp/src/index.ts
  packages/mcp/tsconfig.json
Labels: ✨ enhancement

#5782 🛠️ ci: Add Workflow to Detect Unused i18next Keys in PRs
  .github/workflows/i18n-unused-keys.yml
Labels: 🤖 ci/cd

#5791 📦 chore: Bump Packages
  .github/workflows/eslint-ci.yml
  .github/workflows/unused-packages.yml
  api/package.json
  client/package.json
  client/src/utils/artifacts.ts
  package-lock.json
  package.json
  packages/data-provider/src/actions.ts
Labels: 📦 dependencies, 🔧 fix, 🧪 tests

#5803 🔄 chore: Enforce 18next Language Keys
  .github/workflows/i18n-unused-keys.yml
  .gitignore
  client/src/@types/i18next.d.ts
  client/src/common/types.ts
  client/src/components/Chat/Input/Files/Table/Columns.tsx
  client/src/components/Chat/Input/Files/Table/SortFilterHeader.tsx
  client/src/components/Chat/Input/Mention.tsx
  client/src/components/Conversations/Fork.tsx
  client/src/components/Nav/Settings.tsx
  client/src/components/Nav/SettingsTabs/Account/DeleteAccount.tsx
  client/src/components/Nav/SettingsTabs/Commands/PlusCommandSwitch.tsx
  client/src/components/Nav/SettingsTabs/Commands/SlashCommandSwitch.tsx
  client/src/components/SidePanel/Builder/ActionsAuth.tsx
  client/src/components/SidePanel/Parameters/DynamicCheckbox.tsx
  client/src/components/SidePanel/Parameters/DynamicCombobox.tsx
  client/src/components/SidePanel/Parameters/DynamicDropdown.tsx
  client/src/components/SidePanel/Parameters/DynamicInput.tsx
  client/src/components/SidePanel/Parameters/DynamicSlider.tsx
  client/src/components/SidePanel/Parameters/DynamicSwitch.tsx
  client/src/components/SidePanel/Parameters/DynamicTextarea.tsx
  client/src/components/SidePanel/Parameters/OptionHover.tsx
  client/src/components/ui/DataTable.tsx
  client/src/components/ui/ModelParameters.tsx
  client/src/hooks/Conversations/useArchiveHandler.ts
  client/src/hooks/Files/useFileHandling.ts
  client/src/locales/Translation.spec.ts
  client/src/locales/en/translation.json
  client/src/routes/Layouts/DashBreadcrumb.tsx
  client/src/routes/Layouts/Startup.tsx
  eslint.config.mjs
  package-lock.json
  package.json
  packages/data-provider/src/config.ts
Labels: 🌍 i18n, 🔧 fix

#5848 🛡️ chore: patch `elliptic` to address GHSA-vjh7-7g9h-fjfh
  package-lock.json
  package.json
Labels: 🔒 security

#5854 🌏 i18n: fix Traditional Chinese Language Option
  client/src/components/Nav/SettingsTabs/General/General.tsx
  client/src/locales/en/translation.json
Labels: 🔧 fix

#5866 🌍 fix: Enhance i18n Support & Optimize Category Handling
  .github/ISSUE_TEMPLATE/LOCIZE_TRANSLATION_ACCESS_REQUEST.yml
  .github/workflows/i18n-unused-keys.yml
  api/models/Categories.js
  client/package.json
  client/src/components/Nav/SettingsTabs/General/General.tsx
  client/src/hooks/Prompts/useCategories.tsx
  client/src/hooks/useLocalize.ts
  client/src/locales/Translation.spec.ts
  client/src/locales/ar/translation.json
  client/src/locales/de/translation.json
  client/src/locales/en/translation.json
  client/src/locales/es/translation.json
  client/src/locales/et/translation.json
  client/src/locales/fi/translation.json
  client/src/locales/fr/translation.json
  client/src/locales/he/translation.json
  client/src/locales/i18n.ts
  client/src/locales/id/translation.json
  client/src/locales/it/translation.json
  client/src/locales/ja/translation.json
  client/src/locales/ko/translation.json
  client/src/locales/nl/translation.json
  client/src/locales/pl/translation.json
  client/src/locales/pt-BR/translation.json
  client/src/locales/pt-PT/translation.json
  client/src/locales/ru/translation.json
  client/src/locales/sv/translation.json
  client/src/locales/tr/translation.json
  client/src/locales/vi/translation.json
  client/src/locales/zh-Hans/translation.json
  client/src/locales/zh-Hant/translation.json
  package-lock.json
  packages/data-provider/src/types.ts
Labels: 🌍 i18n, 🔧 fix, 🔥 hotfix

#5879 🐞 i18n: Remove Debug Mode
  client/src/locales/i18n.ts
Labels: 🔥 hotfix

#5838 📜 ci: Automate`CHANGELOG.md`
  .github/configuration-release.json
  .github/configuration-unreleased.json
  .github/workflows/generate-release-changelog-pr.yml
  .github/workflows/generate-unreleased-changelog-pr.yml
Labels: 🤖 ci/cd

#5956 ✨ style: Enhance Styling & Accessibility
  api/models/Categories.js
  client/src/components/Prompts/Command.tsx
  client/src/components/Prompts/Description.tsx
  client/src/components/Prompts/Groups/List.tsx
  client/src/components/Prompts/PromptEditor.tsx
  client/src/components/Prompts/PromptForm.tsx
  client/src/components/Prompts/PromptVariables.tsx
  client/src/components/SidePanel/Agents/ModelPanel.tsx
  client/src/components/ui/SelectDropDown.tsx
Labels: ♿ a11y, 🎨 design

#5948 🔢 chore: Remove Dollar Sign from Balance Display
  client/src/components/Nav/AccountSettings.tsx
Labels: 🔧 fix

#5392 🌟 feat: Enhance User Experience and SEO with Accessibility Updates and robots.txt
  api/package.json
  api/server/utils/staticCache.js
  client/index.html
  client/package.json
  client/public/robots.txt
  client/src/components/Chat/Input/AudioRecorder.tsx
  client/src/components/Conversations/ConvoOptions/ConvoOptions.tsx
  client/src/components/SidePanel/SidePanel.tsx
  client/vite.config.ts
  index.html
  package-lock.json
Labels: ✨ enhancement, ⚡ performance

#5870 🚀 feat: Add Custom Welcome Message in `librechat.yaml`
  api/server/services/start/interface.js
  client/src/components/Chat/Landing.tsx
  librechat.example.yaml
  packages/data-provider/src/config.ts
Labels: ✨ enhancement

#6022 🚀 feat: Add Georgian Language and Update Fallback Languages
  client/src/components/Nav/SettingsTabs/General/General.tsx
  client/src/locales/en/translation.json
  client/src/locales/i18n.ts
  client/src/locales/ka/translation.json
Labels: ✨ enhancement, 🌍 i18n
