Repository danny-avila/LibreChat, pull requests merged in 2025-06, with the labels that each got.

#7657 🖼️ feat: Avatar GIF Support & Dynamic Extensions
  api/server/controllers/agents/v1.js
  api/server/services/Files/Azure/images.js
  api/server/services/Files/Firebase/images.js
  api/server/services/Files/Local/images.js
  api/server/services/Files/S3/images.js
  api/server/services/Files/images/avatar.js
  client/src/components/SidePanel/Agents/Images.tsx
Labels: ✨ enhancement

#7788 🎨 refactor: Enhance UI Consistency, Accessibility & Localization
  client/src/components/Bookmarks/DeleteBookmarkButton.tsx
  client/src/components/Bookmarks/EditBookmarkButton.tsx
  client/src/components/Chat/Messages/SiblingSwitch.tsx
  client/src/components/SidePanel/Bookmarks/BookmarkTableRow.tsx
  client/src/components/SidePanel/Memories/MemoryEditDialog.tsx
  client/src/components/SidePanel/Memories/MemoryViewer.tsx
  client/src/components/ui/OGDialogTemplate.tsx
  client/src/locales/en/translation.json
Labels: ♿ a11y, 🎨 design

#7899 🚮 feat: Enhance "Delete User" Script
  config/delete-user.js
Labels: 🔧 fix

#8014 🤩 style: DialogImage, Update Stylesheet, and Improve Accessibility
  client/src/components/Chat/Messages/Content/DialogImage.tsx
  client/src/locales/en/translation.json
  client/src/style.css
Labels: ♿ a11y, 🔧 fix, 🎨 design
