Repository danny-avila/LibreChat, pull requests merged in 2025-03, with the labels that each got.

#6219 🌍 i18n: Add Thai Language Support and Update Translations
  README.md
  client/src/components/Nav/SettingsTabs/General/General.tsx
  client/src/locales/en/translation.json
  client/src/locales/i18n.ts
  client/src/locales/th/translation.json
Labels: 🌍 i18n

#6245 🔧 fix: MeiliSearch Field Error and Patch Incorrect Import by #6210
  api/lib/db/indexSync.js
  api/models/plugins/mongoMeili.js
Labels: 🔧 fix

#6247 🔏 fix: Enhance Two-Factor Authentication
  api/server/controllers/TwoFactorController.js
  api/server/controllers/auth/LoginController.js
  api/server/controllers/auth/TwoFactorAuthController.js
  client/src/components/Nav/SettingsTabs/Account/Account.tsx
  client/src/components/Nav/SettingsTabs/Account/DisableTwoFactorToggle.tsx
  client/src/components/Nav/SettingsTabs/Account/TwoFactorAuthentication.tsx
  client/src/components/Nav/SettingsTabs/Account/TwoFactorPhases/DisablePhase.tsx
  client/src/components/Nav/SettingsTabs/Account/TwoFactorPhases/SetupPhase.tsx
  package-lock.json
  packages/data-provider/src/types.ts
  packages/data-schemas/LICENSE
  packages/data-schemas/README.md
  packages/data-schemas/package.json
  packages/data-schemas/src/index.ts
  packages/data-schemas/src/schema/user.ts
Labels: 🔧 fix, 🔥 hotfix

#6294 🎨 a11y: Update Model Spec Description Text
  client/src/components/Chat/Menus/Models/ModelSpec.tsx
Labels: ♿ a11y

#6316 🔧 fix: comment out MCP servers to resolve service run issues
  librechat.example.yaml
Labels: 🔧 fix

#6142 🚀 feat: `S3` Integration for File handling and Image uploads
  .env.example
  api/package.json
  api/server/services/AppService.js
  api/server/services/Files/S3/crud.js
  api/server/services/Files/S3/images.js
  api/server/services/Files/S3/index.js
  api/server/services/Files/S3/initialize.js
  api/server/services/Files/strategies.js
  librechat.example.yaml
  package-lock.json
Labels: ✨ enhancement

#6153 🚀 feat: Integrate `Azure Blob Storage` for file handling and image uploads
  .env.example
  api/package.json
  api/server/services/AppService.js
  api/server/services/Files/Azure/crud.js
  api/server/services/Files/Azure/images.js
  api/server/services/Files/Azure/index.js
  api/server/services/Files/Azure/initialize.js
  api/server/services/Files/strategies.js
  package-lock.json
Labels: ✨ enhancement

#6431 🚀 feat: Add support for custom `AWS` endpoint in `S3`
  .env.example
  api/server/services/Files/S3/initialize.js
Labels: ✨ enhancement

#6432 🔐 fix: Invalid Key Length in 2FA Encryption
  api/server/controllers/TwoFactorController.js
  api/server/controllers/auth/TwoFactorAuthController.js
  api/server/routes/auth.js
  api/server/services/twoFactorService.js
  api/server/utils/crypto.js
Labels: 🔥 hotfix

#6438 🚀 feat: Add support for LDAP STARTTLS in LDAP authentication
  .env.example
  api/strategies/ldapStrategy.js
Labels: ✨ enhancement

#6455 🚀 feat: Refactor schema exports and update package version to 0.0.4
  package-lock.json
  packages/data-schemas/package.json
  packages/data-schemas/rollup.config.js
  packages/data-schemas/src/index.ts
  packages/data-schemas/tsconfig.json
Labels: 🐛 bug, 🔨 refactor

#6452 💵 feat: Add Automatic Balance Refill
  .env.example
  api/app/clients/BaseClient.js
  api/app/clients/PluginsClient.js
  api/app/clients/callbacks/createStartHandler.js
  api/app/clients/specs/OpenAIClient.test.js
  api/models/Balance.js
  api/models/Transaction.js
  api/models/Transaction.spec.js
  api/models/spendTokens.spec.js
  api/models/userMethods.js
  api/server/controllers/assistants/chatV1.js
  api/server/controllers/assistants/chatV2.js
  api/server/routes/config.js
  api/server/services/AppService.js
  api/server/services/AppService.spec.js
  api/server/services/Config/getCustomConfig.js
  client/src/components/Nav/AccountSettings.tsx
  client/src/hooks/SSE/useSSE.ts
  librechat.example.yaml
  package-lock.json
  packages/data-provider/package.json
  packages/data-provider/src/config.ts
  packages/data-schemas/package.json
  packages/data-schemas/src/schema/balance.ts
Labels: ✨ enhancement

#6480 🏗️ fix: Fix Agents Token Spend Race Conditions, Expand Test Coverage
  api/app/clients/BaseClient.js
  api/app/clients/OpenAIClient.js
  api/app/clients/PluginsClient.js
  api/app/clients/callbacks/createStartHandler.js
  api/models/Balance.js
  api/models/Transaction.js
  api/models/balanceMethods.js
  api/models/checkBalance.js
  api/models/spendTokens.js
  api/models/spendTokens.spec.js
  api/server/controllers/agents/client.js
  api/server/controllers/assistants/chatV1.js
  api/server/controllers/assistants/chatV2.js
Labels: 🔧 fix

#6534 🔧 fix: Update username reference to use user.name in greeting display
  client/src/components/Chat/Landing.tsx
Labels: 🔧 fix, 🎨 design

#6540 🎨 fix(style): Update background color of CodeBlock component to gray-900
  client/src/components/Messages/Content/CodeBlock.tsx
Labels: 🔥 hotfix, 🎨 design

#6547 🔧 chore: `Vite` Plugin Upgrades & Config Optimizations
  client/package.json
  client/vite.config.ts
  package-lock.json
  package.json
Labels: 🧹 chore

#6508 🌍 feat: Add support for Hungarian language localization
  client/src/components/Nav/SettingsTabs/General/General.tsx
  client/src/locales/en/translation.json
  client/src/locales/hu/translation.json
  client/src/locales/i18n.ts
Labels: 🌍 i18n

#6575 🔧 fix: Azure Blob Integration and File Source References
  .gitignore
  api/server/services/AppService.js
  api/server/services/Files/Azure/crud.js
  api/server/services/Files/images/encode.js
  api/server/services/Files/process.js
  api/server/services/Files/strategies.js
  client/src/components/Chat/Input/Files/SourceIcon.tsx
  client/src/hooks/Endpoint/useSelectorEffects.ts
  packages/data-provider/src/types/files.ts
Labels: 🔧 fix
