Repository danny-avila/LibreChat, pull requests merged in 2025-04, with the labels that each got.

#6669 🌍 i18n: Add Persian Localization Support
  client/src/components/Nav/SettingsTabs/General/General.tsx
  client/src/locales/ar/translation.json
  client/src/locales/cs/translation.json
  client/src/locales/de/translation.json
  client/src/locales/en/translation.json
  client/src/locales/es/translation.json
  client/src/locales/et/translation.json
  client/src/locales/fa/translation.json
  client/src/locales/fi/translation.json
  client/src/locales/fr/translation.json
  client/src/locales/he/translation.json
  client/src/locales/i18n.ts
  client/src/locales/id/translation.json
  client/src/locales/it/translation.json
  client/src/locales/ja/translation.json
  client/src/locales/ka/translation.json
  client/src/locales/ko/translation.json
  client/src/locales/nl/translation.json
  client/src/locales/pl/translation.json
  client/src/locales/pt-BR/translation.json
  client/src/locales/pt-PT/translation.json
  client/src/locales/ru/translation.json
  client/src/locales/sv/translation.json
  client/src/locales/th/translation.json
  client/src/locales/tr/translation.json
  client/src/locales/vi/translation.json
  client/src/locales/zh-Hans/translation.json
  client/src/locales/zh-Hant/translation.json
Labels: 🌍 i18n

#6685 🧹 chore: Update ESLint rules for React hooks
  eslint.config.mjs
Labels: 🔧 fix

#6709 🗑️ a11y: Add Accessible Name to Button for File Attachment Removal
  client/src/components/Chat/Input/Files/RemoveFile.tsx
  client/src/locales/en/translation.json
Labels: ♿ a11y

#6707 🔄 fix: Improve audio MIME type detection and handling
  client/src/hooks/Input/useSpeechToTextExternal.ts
Labels: 🔧 fix

#6487 🪺 refactor: Nest Permission fields for Roles
  api/models/Role.js
  api/models/Role.spec.js
  api/server/middleware/roles/generateCheckAccess.js
  client/src/hooks/Roles/useHasAccess.ts
  package-lock.json
  packages/data-provider/src/index.ts
  packages/data-provider/src/permissions.ts
  packages/data-provider/src/roles.ts
  packages/data-provider/src/types/mutations.ts
  packages/data-schemas/package.json
  packages/data-schemas/src/schema/role.ts
Labels: 🔨 refactor

#6482 📦 chore: Update `caniuse-lite` dependency to version 1.0.30001706
  package-lock.json
Labels: 🧹 chore

#6833 ✨ fix: Implement dynamic text sizing for greeting and name display
  client/src/components/Chat/Landing.tsx
Labels: 🔧 fix
