Repository danny-avila/LibreChat, pull requests merged in 2025-05, with the labels that each got.

#7198 ✨ feat: Enhance form submission for touch screens
  api/app/clients/AnthropicClient.js
  api/utils/tokens.js
  client/src/components/Chat/ExportAndShareMenu.tsx
  client/src/components/Chat/Input/ChatForm.tsx
  client/src/components/Chat/Input/CollapseChat.tsx
  client/src/components/Chat/Messages/Content/EditMessage.tsx
  client/src/hooks/Chat/useFocusChatEffect.ts
Labels: 🎨 design

#7373 🌍 i18n: Add `Danish` and `Czech` and `Catalan` localization support
  client/src/components/Nav/SettingsTabs/General/General.tsx
  client/src/locales/ca/translation.json
  client/src/locales/da/translation.json
  client/src/locales/en/translation.json
  client/src/locales/i18n.ts
Labels: 🌍 i18n

#7308 🎨 feat: add `copy-tex` to improve copying KaTeX
  client/src/main.jsx
Labels: 🎨 design

#7377 🔒 feat: Add Content Security Policy using Helmet middleware
  api/package.json
  api/server/index.js
  api/server/services/start/turnstile.js
  client/src/components/Auth/LoginForm.tsx
  client/src/components/Auth/Registration.tsx
  package-lock.json
Labels: 🔒 security

#6537 💸 feat: Balance Tab in Settings Dialog
  api/server/controllers/Balance.js
  client/src/components/Auth/LoginForm.tsx
  client/src/components/Nav/AccountSettings.tsx
  client/src/components/Nav/Settings.tsx
  client/src/components/Nav/SettingsTabs/Balance/AutoRefillSettings.tsx
  client/src/components/Nav/SettingsTabs/Balance/Balance.tsx
  client/src/components/Nav/SettingsTabs/Balance/TokenCreditsItem.tsx
  client/src/components/Nav/SettingsTabs/index.ts
  client/src/data-provider/Misc/queries.ts
  client/src/hooks/useLocalize.ts
  client/src/locales/en/translation.json
  packages/data-provider/src/config.ts
  packages/data-provider/src/data-service.ts
  packages/data-provider/src/types.ts
Labels: ✨ enhancement

#7630 🔧 fix: Update `xml-crypto` dependencies in package-lock.json
  package-lock.json
Labels: 🔒 security
